pc4-linux@pc4-linux:~/Pobrane$ sudo python3 symulacja_scada.py 
Cannot find device "veth1"
Traceback (most recent call last):
  File "symulacja_scada.py", line 124, in <module>
    main()
  File "symulacja_scada.py", line 95, in main
    setup_network()
  File "symulacja_scada.py", line 41, in setup_network
    run_cmd('ip link set veth1 netns ns_client_s7')
  File "symulacja_scada.py", line 16, in run_cmd
    subprocess.run(cmd, shell=True, check=True)
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'ip link set veth1 netns ns_client_s7' returned non-zero exit status 1.
