c4-linux@pc4-linux:~/Pulpit$ sudo ./ot_simulation.sh
Konfiguracja przestrzeni nazw sieciowych i interfejsów...
Invalid extack attribute
RTNETLINK answers: Numerical result out of range
Cannot find device "veth_ns_iec104"
Cannot find device "veth_ns_iec104"
Cannot find device "veth_ns_iec104"
Cannot find device "veth_host_iec104"
Error: Nexthop has invalid gateway.
Invalid extack attribute
RTNETLINK answers: Numerical result out of range
Cannot find device "veth_ns_modbus"
Cannot find device "veth_ns_modbus"
Cannot find device "veth_ns_modbus"
Cannot find device "veth_host_modbus"
Error: Nexthop has invalid gateway.
Włączanie przekazywania IP...
net.ipv4.ip_forward = 1
Device "veth_ns_iec104" does not exist.
Tworzenie serwera dla protokołu iec104 w ns_iec104...
Tworzenie serwera dla protokołu vnc w ns_vnc...
Tworzenie serwera dla protokołu ntp w ns_ntp...
Device "veth_ns_modbus" does not exist.
Tworzenie serwera dla protokołu modbus w ns_modbus...
Tworzenie serwera dla protokołu s7 w ns_s7...
Tworzenie klientów na hoście...
Device "veth_ns_iec104" does not exist.
Tworzenie klienta dla protokołu iec104...
Tworzenie klienta dla protokołu vnc...
Tworzenie klienta dla protokołu ntp...
Device "veth_ns_modbus" does not exist.
Tworzenie klienta dla protokołu modbus...
Tworzenie klienta dla protokołu s7...
Uruchamianie serwerów w przestrzeniach nazw...
Uruchamianie klientów na hoście...
Symulacja protokołów OT jest uruchomiona.
Aby zatrzymać symulację, użyj polecenia 'pkill -f client_' i 'pkill -f server_'

Aby monitorować ruch, użyj polecenia 'tcpdump' na interfejsach veth lub ens37.
pc4-linux@pc4-linux:~/Pulpit$ Symulacja serwera iec104 uruchomiona na :2404
Symulacja serwera vnc uruchomiona na 192.168.81.3:5900
Symulacja serwera ntp uruchomiona na 192.168.81.4:123
Symulacja serwera s7 uruchomiona na 192.168.81.6:102
ERROR:pymodbus.client.sync:Connection to (, 502) failed: [Errno -2] Name or service not known
ERROR:pymodbus.client.sync:Connection to (, 502) failed: [Errno -2] Name or service not known
Traceback (most recent call last):
  File "client_iec104.py", line 22, in <module>
    simulate_client()
  File "client_iec104.py", line 8, in simulate_client
    s.connect(('', 2404))
ConnectionRefusedError: [Errno 111] Connection refused
Traceback (most recent call last):
  File "client_modbus.py", line 34, in <module>
    run_client()
  File "client_modbus.py", line 23, in run_client
    client.write_coil(coil_addr, coil_value)
  File "/usr/local/lib/python3.8/dist-packages/pymodbus/client/common.py", line 70, in write_coil
    return self.execute(request)
  File "/usr/local/lib/python3.8/dist-packages/pymodbus/client/sync.py", line 108, in execute
    raise ConnectionException("Failed to connect[%s]" % (self.__str__()))
pymodbus.exceptions.ConnectionException: Modbus Error: [Connection] Failed to connect[ModbusTcpClient(:502)]
Traceback (most recent call last):
  File "client_vnc.py", line 22, in <module>
    simulate_client()
  File "client_vnc.py", line 8, in simulate_client
    s.connect(('192.168.81.3', 5900))
OSError: [Errno 113] No route to host
Traceback (most recent call last):
  File "client_ntp.py", line 22, in <module>
    simulate_client()
  File "client_ntp.py", line 8, in simulate_client
    s.connect(('192.168.81.4', 123))
OSError: [Errno 113] No route to host
Traceback (most recent call last):
  File "client_s7.py", line 22, in <module>
    simulate_client()
  File "client_s7.py", line 8, in simulate_client
    s.connect(('192.168.81.6', 102))
OSError: [Errno 113] No route to host

